webtalk_init -webtalk_dir C:/Users/jofad/Documents/GitHub/VS Code/Digital-electronics-1/Labs/project/hall_sensor/hall_sensor.sim/sim_1/behav/xsim/xsim.dir/tb_hall_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr 26 21:09:57 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1591a2c0-b422-491a-8bf2-9264fb6cf4c7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "be4f96800059460abcb025f0327d30c8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "128" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "250 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "23.33_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14664_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3748427758 -regid "" -xml C:/Users/jofad/Documents/GitHub/VS Code/Digital-electronics-1/Labs/project/hall_sensor/hall_sensor.sim/sim_1/behav/xsim/xsim.dir/tb_hall_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/jofad/Documents/GitHub/VS Code/Digital-electronics-1/Labs/project/hall_sensor/hall_sensor.sim/sim_1/behav/xsim/xsim.dir/tb_hall_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/jofad/Documents/GitHub/VS Code/Digital-electronics-1/Labs/project/hall_sensor/hall_sensor.sim/sim_1/behav/xsim/xsim.dir/tb_hall_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
